language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- '3.5'
env:
  global:
  - CFLAGS="-O0"
  - PYTHONDONTWRITEBYTECODE=1
  - secure: XaKF8soCCvw1sWjwhI3KxfthhoXE2mIkEmbCp+MsEt1RtGE0ut2DRv83BNJpEq5At9Lg+5u04KW874L5Wfd2W5lZkYTTP254/2ChULnrePTSZnsyn5M1ALFPKI3o2gVvwgBKKMG3X6Yu6khlkOvlkp5EMyZxMxOBSPkCdjDgGvGe9u+bRkqDrEej3qBW9OmEd1l83Qr/imXtTMI51BLSLUlAfZWhi25Tn3MKSR5dHG4bEq0mdZtCXSrJfUdVOkmw5t44wJSYwmGLnrhcldLOIU2uDV3FEPlGhv92P4EC5J+sRFTztbhKKOiu4hJBw6KgRZV3jp8bWobVSoysQLRz+oY+ZoRtpzkXvll3Bn5pRieUcAAwYpbzhoee8bY7VY/DHJuWvI7Pc8Vfu7cbi0/h3/eV3HG4e5g42veGR3jAf3qI4XEQWRDGCRS5lZm12tbSxpD2ECJn+DODHL4PIdfr0PKk/1yMNK0dPheRlnR0l3/qEPI9gKNSM9PpEoN8Gdvq6FgmEgeXSVXnPPktgydBirAyDLCklN3lADBDq8N62mbom2EpQ69wxhCnsOkmfHScQ3O/C7qZUl7CDQLCb7eeZ0W3gIQP88OFiF/r9xHSbawabCtTVR+lG5srkyePAW+Y7NPtsyp7du95bPhvz9fY3yApbz8cOA6iii+1uY+LMLA=
install:
- pip install -r requirements.txt
- pip install -r requirements-test.txt
- pip install coveralls
script: make test
after_success: coveralls
