language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- '3.5'
env:
  global:
  - CFLAGS="-O0"
  - PYTHONDONTWRITEBYTECODE=1
  - secure: yYg1UWOJOAhFLqtiR2Thhz0myf5d19qhfOQ6uI40f/+0WQi5u06wNUduxEScLCcSJgH6YLtyqeS8tBVvMTanl0gX337fNXUH1VDUW+A/ltRlKieHQPfreQkvgQ1Nwkx3TuEckd5eWyWKkJ6WDMHi80VEIgJnU3lh1NA7rW7+M3JMCl8fOsOd+D9vzhbZ6QeIYKbpCiVBmzs6fTVNn/1OCt+ZcfwV218QRR+wvFWaa1PFqdq43i1kXJeKm57jhLzY1Lum+GxJPTQIm6nFWg2ey8J4DAL4PLW4ZwqpBwL9MKOcv9qDpOIwAXInNAFM1QZdAARS2wKCtad5YhqFFwmfwDCYf2UcGsmlUfH7ktbP8+D3vJYh2ErqwZBUNAEgNfQLATNkDpQWtNDGhZYcnJHAUr1wg+vd1jBTo0PWgfqUTXdhEon9eQP2M8ZrBovWsoDsR1BB0onSh683K0jjVcrX1WQ/smdyvfTGRqkrzcJZJBOQk1TPL57JCgimfHR/dohGxNoyaTi1PsQEW08Tf7lMw4EhqoR5liclFnCqqRv5E9r+aGNEqVtZIcZnCUXqw1asp4D9Fz5SJoZR1TjN0sgKzuj3ijCbG5lhh/ReJSn4biHvrxVQ+EkNRrXAj+vh5D64Hp8tDUnt4mPH52Jy+h6exaZo8q54Hjz/9NJDkTZPSWQ=
install:
- pip install -r requirements.txt
- pip install -r requirements-test.txt
- pip install coveralls
script: make test
after_success: coveralls
