language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - "pip install --user -r requirements.txt"
  - "pip install --user -r test-requirements.txt"
# command to run tests
script: make test